version: '3'
services:
  horizon-server:
    image: horizonprivateserver/horizon-server
    container_name: horizon-server
    environment:
      - MIDDLEWARE_SERVER_IP=${HORIZON_MIDDLEWARE_SERVER_IP}
      - APP_ID=${HORIZON_APP_ID}
      - MIDDLEWARE_USER=${HORIZON_MIDDLEWARE_USER}
      - MIDDLEWARE_PASSWORD=${HORIZON_MIDDLEWARE_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${HORIZON_ASPNETCORE_ENVIRONMENT}
    ports:
      - "10071:10071"
      - "10075:10075"
      - "10077:10077"
      - "10078:10078"
      - "10073:10073"
      - "8281:8281"
      - "8765:8765"
      - "50000-50100:50000-50100/udp"
      - "10070:10070/udp"
    volumes:
      - "./logs:/logs"
      - ./dme.json:/dme/dme.json
      - ./medius.json:/medius/medius.json
      - ./muis.json:/muis/muis.json
      - ./db.config.json:/db.config.json
      # plugins
      # - ${HORIZON_MEDIUS_PLUGIN_PATH}:/medius/plugins/
      # - ${HORIZON_DME_PLUGIN_PATH}:/dme/plugins/
      # - ${HORIZON_PATCH_MISC_PATH}:/medius/plugins/bin/
      # - ${HORIZON_PATCH_BIN_PATH}:/medius/plugins/bin/patch/
    network_mode: bridge

  horizon-middleware:
    image: horizonprivateserver/horizon-server-database-middleware
    container_name: horizon-middleware
    environment:
      - HORIZON_DB_USER=${HORIZON_DB_USER}
      - HORIZON_MSSQL_SA_PASSWORD=${HORIZON_MSSQL_SA_PASSWORD}
      - HORIZON_DB_NAME=${HORIZON_DB_NAME}
      - HORIZON_DB_SERVER=${HORIZON_DB_SERVER}
      - ASPNETCORE_ENVIRONMENT=${HORIZON_ASPNETCORE_ENVIRONMENT}
      - HORIZON_MIDDLEWARE_SERVER=${HORIZON_MIDDLEWARE_SERVER}
      - HORIZON_MIDDLEWARE_USER=${HORIZON_MIDDLEWARE_USER}
      - HORIZON_MIDDLEWARE_PASSWORD=${HORIZON_MIDDLEWARE_PASSWORD}
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./appsettings.json:/appsettings.json
    network_mode: bridge

  horizon-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: horizon-database
    environment:
      - ACCEPT_EULA=True
      - MSSQL_SA_PASSWORD=${HORIZON_MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./database_data:/var/opt/mssql
      - ./database_backup:/backup
    user: root
    network_mode: bridge